# Generated by Django 4.0 on 2021-12-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211207_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='step',
            field=models.IntegerField(default=0, verbose_name='Step'),
        ),
    ]
