# Generated by Django 4.0 on 2021-12-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_complaint_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'complaint', 'verbose_name_plural': 'complaints'},
        ),
    ]
