# Generated by Django 4.0 on 2021-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='closed_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Closed Date'),
        ),
    ]
