# Generated by Django 3.2.10 on 2021-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20211211_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='extracrdt',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='EXTRACRDT'),
        ),
    ]
