# Generated by Django 3.2.10 on 2021-12-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20211211_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propdocument',
            old_name='boro',
            new_name='borough',
        ),
        migrations.AddField(
            model_name='propdocument',
            name='doc_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='DOC_TYPE'),
        ),
        migrations.AddField(
            model_name='propdocument',
            name='document_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='DOC.AMOUNT'),
        ),
        migrations.AddField(
            model_name='propdocument',
            name='document_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='DOC.DATE'),
        ),
        migrations.AddField(
            model_name='propdocument',
            name='percent_trans',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='RECORDED / FILED'),
        ),
        migrations.AddField(
            model_name='propdocument',
            name='recorded_borough',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Recorded Borough'),
        ),
        migrations.AddField(
            model_name='propdocument',
            name='recorded_datetime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='RECORDED / FILED'),
        ),
    ]
