# Generated by Django 3.2.10 on 2021-12-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20211212_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='propdocument',
            name='good_through_date',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='GOOD THROUGH DATE'),
        ),
        migrations.AlterField(
            model_name='propdocument',
            name='percent_trans',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='% TRANSFERRED'),
        ),
    ]
