# Generated by Django 3.2.10 on 2021-12-11 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20211212_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='propdocument',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propdocument',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
