# Generated by Django 3.2.10 on 2021-12-11 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20211212_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='timestamp',
            new_name='timestamp_created',
        ),
        migrations.AddField(
            model_name='complaint',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='propdocument',
            name='step',
            field=models.IntegerField(default=0, verbose_name='Step'),
        ),
        migrations.AddField(
            model_name='property',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
