# Generated by Django 3.2.10 on 2021-12-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20211212_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bbl',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='BBL'),
        ),
    ]
