# Generated by Django 3.2.10 on 2021-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_property_extracrdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=None, verbose_name='Csv')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status', models.IntegerField(choices=[('PENDING', 0), ('SUCCESS', 1), ('FAILURE', 2)], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'csv',
                'verbose_name_plural': 'csvs',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parid', models.CharField(max_length=64, verbose_name='PARID')),
                ('borough', models.CharField(blank=True, max_length=64, null=True, verbose_name='BORO')),
                ('block', models.CharField(blank=True, max_length=64, null=True, verbose_name='BLOCK')),
                ('lot', models.CharField(blank=True, max_length=64, null=True, verbose_name='LOT')),
                ('owner', models.CharField(blank=True, max_length=64, null=True, verbose_name='OWNER')),
                ('housenum_lo', models.CharField(blank=True, max_length=64, null=True, verbose_name='HOUSENUM_LO')),
                ('housenum_hi', models.CharField(blank=True, max_length=64, null=True, verbose_name='HOUSENUM_HI')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('zoning', models.CharField(blank=True, max_length=64, null=True, verbose_name='ZONING')),
                ('zip_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='ZIP_CODE')),
                ('bld_story', models.CharField(blank=True, max_length=64, null=True, verbose_name='BLD_STORY')),
                ('bldg_class', models.CharField(blank=True, max_length=64, null=True, verbose_name='BLDG_CLASS')),
                ('units', models.CharField(blank=True, max_length=64, null=True, verbose_name='UNITS')),
                ('lot_frt', models.CharField(blank=True, max_length=64, null=True, verbose_name='LOT_FRT')),
                ('lot_dep', models.CharField(blank=True, max_length=64, null=True, verbose_name='LOT_DEP')),
                ('bld_frt', models.CharField(blank=True, max_length=64, null=True, verbose_name='BLD_FRT')),
                ('bld_dep', models.CharField(blank=True, max_length=64, null=True, verbose_name='BLD_DEP')),
                ('land_area', models.CharField(blank=True, max_length=64, null=True, verbose_name='LAND_AREA')),
                ('gross_sqft', models.CharField(blank=True, max_length=64, null=True, verbose_name='GROSS_SQFT')),
                ('pymkttot', models.CharField(blank=True, max_length=64, null=True, verbose_name='PYMKTTOT')),
                ('curmkttot', models.CharField(blank=True, max_length=64, null=True, verbose_name='PYMKTTOT')),
            ],
            options={
                'verbose_name': 'output',
                'verbose_name_plural': 'outputs',
            },
        ),
    ]
