# Generated by Django 3.2.10 on 2021-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_csv_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='status',
            field=models.IntegerField(choices=[('PENDING', 0), ('PROCESSING', 1), ('SUCCESS', 2), ('FAILURE', 3)], default=0, verbose_name='Status'),
        ),
    ]
