# Generated by Django 3.2.10 on 2021-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_csv_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='DOCUMENT ID')),
                ('record_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='RECORD TYPE')),
                ('party_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='PARTY TYPE')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='NAME')),
                ('address_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ADDRESS 1')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ADDRESS 2')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='COUNTRY')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='CITY')),
                ('zip', models.CharField(blank=True, max_length=200, null=True, verbose_name='ZIP')),
                ('good_through_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='GOOD THROUGH DATE')),
            ],
            options={
                'verbose_name': 'party',
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.AlterField(
            model_name='csv',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'PROCESSING'), (2, 'SUCCESS'), (3, 'FAILURE')], default=0, verbose_name='Status'),
        ),
    ]
