# Generated by Django 3.2.10 on 2021-12-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20211216_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NAME_2'),
        ),
    ]
