# Generated by Django 3.2.10 on 2021-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_party_name_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='STATE'),
        ),
    ]
