# Generated by Django 3.2.10 on 2021-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_party_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='oldest_created_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oldest Created Date'),
        ),
    ]
