# Generated by Django 3.2.10 on 2021-12-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_complaint_oldest_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='complaint',
        ),
    ]
